Run install script on azure pipeline.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -13,10 +13,8 @@ jobs:
     vmImage: macOS-10.14
 
   steps:
-  - script: echo Hello, world!
-    displayName: 'Run a one-line script'
-
-  - script: |
-      echo Add other tasks to build, test, and deploy your project.
-      echo See https://aka.ms/yaml
-    displayName: 'Run a multi-line script'
+  - bash: |
+      # Exit immediately if a command exits with a non-zero status.
+      set -e
+      sh install.sh
+    displayName: 'Run install script'
